version: "3"
services:
  app:
    container_name: StationSki
    image: mohaamedamine/backend  # Replace with the actual image and tag
    restart: on-failure
    environment:
       SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:mysql://mysqldatabase:3306/devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
             "spring.datasource.username" : "root",
             "spring.datasource.password" : "root",
             "spring.jpa.show-sql" : "true",
             "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.properties.hi
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb  # Ensure the MySQL service is started before the application
    volumes:
      - app_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
    app_data:  # Define the app_data volume
    db:
