version: "3"
services:
  app:
    container_name: backend
    image: mohaamedamine/backend  # Replace with the actual image and tag
    restart: on-failure
   environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"  # Map your application's port to the host
    depends_on:
      - mysqldb  # Ensure the MySQL service is started before the application
    volumes:
      - app_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

    volumes:
      - db:/var/lib/mysql



volumes:
  app_data:  # Define the app_data volume
  db:
