version: "3"

services:
  app:
    container_name: stationSki
    image: mohaamedamine/backend  # Remplacez par l'image et le tag réels
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",  # Définissez le mot de passe souhaité
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    volumes:
      - app_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Autoriser un mot de passe vide pour root
      MYSQL_DATABASE: "stationSki"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  app_data:
  db:
