version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD : root 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    image: mohaamedamine/backend
    container_name: spring_app_container
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
       - app_data:/app/data

volumes:
  mysql_data:
  app_data:
