version: "3"
services:
  app:
    container_name: stationSki
    image: mohaamedamine/backend  # Replace with the actual image and tag
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8089:8089"  # Map your application's port to the host
    depends_on:
      - mysqldb  # Ensure the MySQL service is started before the application
    volumes:
      - app_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD= yes
      MYSQL_DATABASE= stationSki
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql


volumes:
    app_data:  # Define the app_data volume
    db:
